/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package advancedimageviewer;

import java.awt.image.BufferedImage;

/**
 *
 * @author Ethan
 */
public class AIVTools extends javax.swing.JFrame {

    public AIVFrame parent;
    /**
     * Creates new form AIVTools
     */
    public AIVTools(AIVFrame p) {
        parent = p;
        setUndecorated(true);
        initComponents();
        setTitle("AIV Tools");
        
        new Thread(){
            public void run(){
                while(true){
                    UpdateSliderData();
                    try{Thread.sleep(100);}catch(Exception ex){}
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider2 = new javax.swing.JSlider();
        jSlider1 = new javax.swing.JSlider();
        openButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        brightnessSlider = new javax.swing.JSlider();
        applyButton = new javax.swing.JButton();
        brightnessInfo = new javax.swing.JLabel();
        contrastSlider = new javax.swing.JSlider();
        contrastInfo = new javax.swing.JLabel();
        gammaSlider = new javax.swing.JSlider();
        gammaInfo = new javax.swing.JLabel();
        rSatSlider = new javax.swing.JSlider();
        rSatInfo = new javax.swing.JLabel();
        gSatSlider = new javax.swing.JSlider();
        gSatInfo = new javax.swing.JLabel();
        bSatSlider = new javax.swing.JSlider();
        bSatInfo = new javax.swing.JLabel();
        defaultButton = new javax.swing.JButton();
        resizeButton = new javax.swing.JButton();
        specialButton = new javax.swing.JButton();
        isoslider = new javax.swing.JSlider();
        isocolinfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        brightnessSlider.setMaximum(200);
        brightnessSlider.setToolTipText("0");
        brightnessSlider.setValue(100);

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        brightnessInfo.setText("Brightness: DEFAULT");

        contrastSlider.setMaximum(200);
        contrastSlider.setValue(100);

        contrastInfo.setText("Contrast: DEFAULT");

        gammaSlider.setMaximum(200);
        gammaSlider.setMinimum(1);
        gammaSlider.setValue(100);

        gammaInfo.setText("Gamma: DEFAULT");

        rSatSlider.setMaximum(200);
        rSatSlider.setValue(100);

        rSatInfo.setText("Red Saturation: DEFAULT");

        gSatSlider.setMaximum(200);
        gSatSlider.setValue(100);

        gSatInfo.setText("Green Saturation: DEFAULT");

        bSatSlider.setMaximum(200);
        bSatSlider.setValue(100);

        bSatInfo.setText("Blue Saturation: DEFAULT");

        defaultButton.setText("Defaults");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });

        resizeButton.setText("Resize");
        resizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeButtonActionPerformed(evt);
            }
        });

        specialButton.setText("Enhance");
        specialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialButtonActionPerformed(evt);
            }
        });

        isoslider.setMajorTickSpacing(1);
        isoslider.setMaximum(3);
        isoslider.setPaintTicks(true);
        isoslider.setSnapToTicks(true);
        isoslider.setValue(0);

        isocolinfo.setText("Isolated Color: DEFAULT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(openButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton))
                            .addComponent(brightnessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brightnessInfo)
                            .addComponent(applyButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rSatInfo)
                                .addComponent(defaultButton, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(resizeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contrastSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contrastInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gSatInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(specialButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gammaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gammaInfo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bSatInfo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isocolinfo)
                    .addComponent(isoslider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openButton)
                    .addComponent(saveButton)
                    .addComponent(resizeButton))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(brightnessInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(brightnessSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rSatInfo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contrastInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contrastSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gSatInfo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gammaInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gammaSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bSatInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bSatSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isocolinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isoslider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applyButton)
                    .addComponent(defaultButton)
                    .addComponent(specialButton))
                .addContainerGap())
        );

        brightnessSlider.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        BufferedImage bi = AdvancedImageViewer.OpenImage();
        if(bi == null) return;
        parent.img = bi;
        parent.vimg = parent.img; 
        defaultButtonActionPerformed(evt);
        parent.formToImage();
        parent.repaint();
    }//GEN-LAST:event_openButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        AdvancedImageViewer.SaveImage(parent.vimg);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        parent.applyColorProfile(CollectSettings());
    }//GEN-LAST:event_applyButtonActionPerformed

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        brightnessSlider.setValue(100);
        contrastSlider.setValue(100);
        gammaSlider.setValue(100);
        rSatSlider.setValue(100);
        gSatSlider.setValue(100);
        bSatSlider.setValue(100);
        isoslider.setValue(0);
        UpdateSliderData();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void resizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeButtonActionPerformed
        parent.formToImage();
    }//GEN-LAST:event_resizeButtonActionPerformed

    private void specialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialButtonActionPerformed
       if(parent.enhanceframe == null)
            new AIVEnhance(parent);
       else{
           parent.enhanceframe.dispose();
           parent.enhanceframe = null;
       }
       
       //parent.vimg = ImageProcessor.applyVarianceDots(parent.vimg);
       //parent.repaint();
    }//GEN-LAST:event_specialButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel bSatInfo;
    private javax.swing.JSlider bSatSlider;
    private javax.swing.JLabel brightnessInfo;
    private javax.swing.JSlider brightnessSlider;
    private javax.swing.JLabel contrastInfo;
    private javax.swing.JSlider contrastSlider;
    private javax.swing.JButton defaultButton;
    private javax.swing.JLabel gSatInfo;
    private javax.swing.JSlider gSatSlider;
    private javax.swing.JLabel gammaInfo;
    private javax.swing.JSlider gammaSlider;
    private javax.swing.JLabel isocolinfo;
    private javax.swing.JSlider isoslider;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JButton openButton;
    private javax.swing.JLabel rSatInfo;
    private javax.swing.JSlider rSatSlider;
    private javax.swing.JButton resizeButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton specialButton;
    // End of variables declaration//GEN-END:variables

    private float brightness; //INDEX 0
    private float contrast; //INDEX 1
    private float gamma; //INDEX 2
    private float redsat; //INDEX 3
    private float greensat; //INDEX 4
    private float bluesat; //INDEX 5
    private float isocol; //INDEX 6
    
    private float[] CollectSettings(){
        UpdateSliderData();
        float[] settings = ImageProcessor.defaultColorSettings.clone();
        settings[0] = brightness;
        settings[1] = contrast;
        settings[2] = gamma;
        settings[3] = redsat;
        settings[4] = greensat;
        settings[5] = bluesat;
        settings[6] = isocol;
        return settings;
    }

    private float ConvSliderData(int a){return a/100f;}
    
    private void UpdateSliderData() {
        brightness = ConvSliderData(brightnessSlider.getValue());
        brightnessInfo.setText("Brightness: "+brightness);
        contrast = ConvSliderData(contrastSlider.getValue());
        contrastInfo.setText("Contrast: "+contrast);
        gamma = ConvSliderData(gammaSlider.getValue());
        gammaInfo.setText("Gamma: "+gamma);
        redsat = ConvSliderData(rSatSlider.getValue());
        rSatInfo.setText("Red Saturation: "+redsat);
        greensat = ConvSliderData(gSatSlider.getValue());
        gSatInfo.setText("Green Saturation: "+greensat);
        bluesat = ConvSliderData(bSatSlider.getValue());
        bSatInfo.setText("Blue Saturation: "+bluesat);
        isocol = (float)isoslider.getValue();
        isocolinfo.setText("Isolated Color: "+(isocol==0f?"None":isocol==1f?"Red":isocol==2f?"Green":"Blue"));
    }
}
